# This workflow warns the team about P0 issues immediately when they are created.
name: P0 Issue Alert
on:

  issues:
    types: 
      - labeled

permissions:
  issues: write
  contents: read

jobs: 
  p0_notify_team:
    runs-on: ubuntu-latest
    # Only run for issues labeled with 'p0' (case-insensitive)
    if: >
      (github.event_name == 'issues' && (
          (github.event.label.name == 'p0' || github.event.label.name == 'P0'))
      )

    steps:
      - name:  Harden the runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Notify team of P0 issues
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8.0.0
        with:
          script: |
            const script = require('./.github/scripts/bot-p0-issues-notify-team.js');      
            await script({ github, context});